---
#- name: Define nginx_user.
#  set_fact:
#    nginx_user: "{{ ngx_user }}"
#  when: nginx_user is not defined

# Setup/install tasks.
- include_tasks: setup-redhat.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: setup-ubuntu.yml
  when: ansible_distribution == 'Ubuntu'

# Vhost configuration.
- import_tasks: vhosts.yml
