---
- name: install dependency package
  yum: name={{ item }} state=latest
  with_items:
    - gcc
    - make
    - openssl-devel
    - pcre-devel
    - gd-devel

- name: create nginx group
  group: name={{ ngx_group }} state=present

- name: create nginx user
  user: name={{ ngx_user }} group={{ ngx_user }} shell=/bin/false

- name: copy nginx package to remote host
  copy: src={{ ngx_package }} dest=/tmp/{{ ngx_package }}
  tags: cppkg

- name: tar nginx
  shell: cd /tmp;tar xf {{ ngx_package }}

#- name: compile nginx
#  shell: cd {{ ngx_source_path }} && ./configure  --prefix={{ ngx_path }} --with-file-aio --with-poll_module --with-http_realip_module --with-http_image_filter_module --with-http_gzip_static_module --with-http_addition_module --with-http_sub_module --with-http_dav_module --with-http_flv_module --with-http_slice_module --with-http_mp4_module --with-http_random_index_module --with-http_secure_link_module --with-http_degradation_module --with-http_ssl_module --with-http_stub_status_module --with-http_v2_module && make && make install

- name: copy nginx conf
  template: src=nginx.conf dest={{ ngx_conf_file }}

- name: create nginx link
  file: src={{ ngx_conf_path }} dest=/etc/nginx state=link

- name: mkdir nginx log path
  file: path={{ ngx_log_path }} state=directory

- name: chown permission
  shell: chown -R {{ ngx_user }}:{{ ngx_group }} {{ ngx_path }} {{ ngx_log_path }}

#- name: copy nginx service
#  template: src=redhat.service dest=/etc/init.d/nginx owner={{ ngx_user }} group={{ ngx_user }} mode=0755
#  copy: src=nginx.service dest=/usr/lib/systemd/system/nginx.service owner={{ ngx_user }} group={{ ngx_user }} mode=0755

#- name: nginx service
#  service: name=nginx enabled=yes
#  systemd: name=nginx enabled=yes
#  notify: start nginx

- name: copy nginx service
  template: src=redhat.service dest=/etc/init.d/nginx owner={{ ngx_user }} group={{ ngx_user }} mode=0755
  when: ansible_distribution_major_version <= "6"
  register: result

- name: copy nginx systemd
  template: src=nginx.systemd dest=/usr/lib/systemd/system/nginx.service owner={{ ngx_user }} group={{ ngx_user }} mode=0755
  when: ansible_distribution_major_version >= "7"

- name: nginx service
  service: name=nginx enabled=yes state=started
  when: result is success
  
- name: nginx systemd
  systemd: name=nginx enabled=yes state=started
  when: result is skipped

